export enum DomainEventType {
  // ── Auth ──
  USER_SIGNED_UP = 'USER_SIGNED_UP',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  BUSINESS_ACTIVATED = 'BUSINESS_ACTIVATED',
  DEVELOPER_ACTIVATED = 'DEVELOPER_ACTIVATED',
  MODULE_INSTALLED = 'MODULE_INSTALLED',
  MODULE_UNINSTALLED = 'MODULE_UNINSTALLED',

  // ── Orders ──
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_PREPARING = 'ORDER_PREPARING',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',

  // ── Bookings ──
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_REMINDER = 'BOOKING_REMINDER',

  // ── Payments ──
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  COMMISSION_CHARGED = 'COMMISSION_CHARGED',

  // ── Escrow ──
  ESCROW_CREATED = 'ESCROW_CREATED',
  ESCROW_HELD = 'ESCROW_HELD',
  ESCROW_RELEASED = 'ESCROW_RELEASED',
  ESCROW_REFUNDED = 'ESCROW_REFUNDED',
  ESCROW_DISPUTED = 'ESCROW_DISPUTED',
  ESCROW_PARTIAL_RELEASE = 'ESCROW_PARTIAL_RELEASE',
  ESCROW_MANUAL_RELEASE = 'ESCROW_MANUAL_RELEASE',
  ESCROW_STEP_RELEASE = 'ESCROW_STEP_RELEASE',

  // ── Rentals ──
  RENTAL_CREATED = 'RENTAL_CREATED',
  RENTAL_RETURNED = 'RENTAL_RETURNED',
  RENTAL_OVERDUE = 'RENTAL_OVERDUE',
  RENTAL_RETURN_REMINDER = 'RENTAL_RETURN_REMINDER',
  DEPOSIT_RELEASED = 'DEPOSIT_RELEASED',

  // ── Products / Stock ──
  PRODUCT_PUBLISHED = 'PRODUCT_PUBLISHED',
  PRODUCT_MODIFIED = 'PRODUCT_MODIFIED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  LOW_STOCK = 'LOW_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  BACK_IN_STOCK = 'BACK_IN_STOCK',

  // ── Services ──
  SERVICE_PUBLISHED = 'SERVICE_PUBLISHED',

  // ── Reviews ──
  REVIEW_PUBLISHED = 'REVIEW_PUBLISHED',
  REVIEW_RESPONSE = 'REVIEW_RESPONSE',

  // ── Messages ──
  NEW_MESSAGE = 'NEW_MESSAGE',

  // ── Loyalty / Marketing ──
  LOYALTY_POINTS_EARNED = 'LOYALTY_POINTS_EARNED',
  LOYALTY_TIER_CHANGED = 'LOYALTY_TIER_CHANGED',
  CAMPAIGN_SCHEDULED = 'CAMPAIGN_SCHEDULED',
  CAMPAIGN_SENT = 'CAMPAIGN_SENT',
  PROMOTION_STARTED = 'PROMOTION_STARTED',
  FLASH_SALE_STARTED = 'FLASH_SALE_STARTED',
  CART_ABANDONED = 'CART_ABANDONED',
  CLIENT_INACTIVE = 'CLIENT_INACTIVE',
  CLIENT_BIRTHDAY = 'CLIENT_BIRTHDAY',

  // ── Disputes ──
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',

  // ── Support ──
  SUPPORT_TICKET_CREATED = 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_RESPONDED = 'SUPPORT_TICKET_RESPONDED',
  SUPPORT_TICKET_CLOSED = 'SUPPORT_TICKET_CLOSED',
  ESCALATED_TICKET = 'ESCALATED_TICKET',
  SATISFACTION_SURVEY = 'SATISFACTION_SURVEY',
  SURVEY_RESPONDED = 'SURVEY_RESPONDED',

  // ── Developer ──
  MODULE_SUBMITTED = 'MODULE_SUBMITTED',
  MODULE_APPROVED = 'MODULE_APPROVED',
  MODULE_REJECTED = 'MODULE_REJECTED',
  MODULE_BUG_REPORTED = 'MODULE_BUG_REPORTED',
  DEVELOPER_REVENUE_EARNED = 'DEVELOPER_REVENUE_EARNED',
  DEVELOPER_PAYOUT_PROCESSED = 'DEVELOPER_PAYOUT_PROCESSED',

  // ── Advertising ──
  AD_CREATED = 'AD_CREATED',
  AD_APPROVED = 'AD_APPROVED',
  AD_REJECTED = 'AD_REJECTED',
  AD_COMPLETED = 'AD_COMPLETED',

  // ── Employee ──
  EMPLOYEE_CREATED = 'EMPLOYEE_CREATED',
  EMPLOYEE_ABSENT = 'EMPLOYEE_ABSENT',
  EMPLOYEE_LATE = 'EMPLOYEE_LATE',
  DOCUMENT_EXPIRING = 'DOCUMENT_EXPIRING',
  LEAVE_REQUESTED = 'LEAVE_REQUESTED',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  PAYROLL_PROCESSED = 'PAYROLL_PROCESSED',

  // ── Delivery ──
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  DELIVERY_STARTED = 'DELIVERY_STARTED',
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  DELIVERY_NO_START = 'DELIVERY_NO_START',
  DELIVERY_REASSIGNED = 'DELIVERY_REASSIGNED',

  // ── AfriScore ──
  SCORE_RECALCULATED = 'SCORE_RECALCULATED',
  BADGE_EARNED = 'BADGE_EARNED',
  SCORE_IMPROVED = 'SCORE_IMPROVED',
  SCORE_DECREASED = 'SCORE_DECREASED',

  // ── Security ──
  SECURITY_ALERT = 'SECURITY_ALERT',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  NEW_DEVICE_DETECTED = 'NEW_DEVICE_DETECTED',
  FRAUD_ALERT = 'FRAUD_ALERT',

  // ── System ──
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  BACKUP_FAILED = 'BACKUP_FAILED',

  // ── Events & Training ──
  EVENT_PURCHASED = 'EVENT_PURCHASED',
  TRAINING_PURCHASED = 'TRAINING_PURCHASED',
  UPCOMING_EVENT = 'UPCOMING_EVENT',

  // ── Onboarding ──
  ONBOARDING_COMPLETED = 'ONBOARDING_COMPLETED',
  SETUP_INCOMPLETE = 'SETUP_INCOMPLETE',

  // ── Debt ──
  DEBT_CREATED = 'DEBT_CREATED',
  DEBT_SETTLED = 'DEBT_SETTLED',
  DEBT_OVERDUE = 'DEBT_OVERDUE',

  // ── Subscription ──
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',

  // ── Cart ──
  CART_ITEM_ADDED = 'CART_ITEM_ADDED',
  CART_ITEM_UPDATED = 'CART_ITEM_UPDATED',
  CART_ITEM_REMOVED = 'CART_ITEM_REMOVED',
  CHECKOUT_INITIATED = 'CHECKOUT_INITIATED',
  CHECKOUT_COMPLETED = 'CHECKOUT_COMPLETED',
  COUPON_APPLIED = 'COUPON_APPLIED',

  // ── Referral ──
  REFERRAL_CODE_CREATED = 'REFERRAL_CODE_CREATED',
  REFERRAL_INVITED = 'REFERRAL_INVITED',
  REFERRAL_CONVERTED = 'REFERRAL_CONVERTED',
  REFERRAL_REWARD_AWARDED = 'REFERRAL_REWARD_AWARDED',

  // ── Inventory ──
  INVENTORY_ALERT = 'INVENTORY_ALERT',

  // ── Satisfaction (consolidated with SATISFACTION_SURVEY)
  // SATISFACTION_SURVEY_SENT removed — use SATISFACTION_SURVEY instead

  // ── Admin ──
  DAILY_REPORT_READY = 'DAILY_REPORT_READY',
  WEEKLY_DEV_REPORT = 'WEEKLY_DEV_REPORT',

  // ── Fraude ──
  SCORE_CRITICAL = 'SCORE_CRITICAL',

  // ── Trial ──
  TRIAL_EXPIRING = 'TRIAL_EXPIRING',

  // ── Order Reminders ──
  ORDER_PENDING_REMINDER = 'ORDER_PENDING_REMINDER',
  ORDER_AUTO_CANCELLED = 'ORDER_AUTO_CANCELLED',
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  ORDER_REFUSED = 'ORDER_REFUSED',

  // ── CRM ──
  CLIENT_SEGMENT_CHANGED = 'CLIENT_SEGMENT_CHANGED',
  CLIENT_LIFETIME_VALUE_UPDATED = 'CLIENT_LIFETIME_VALUE_UPDATED',
  NEW_CLIENT = 'NEW_CLIENT',
  LTV_RECALCULATED = 'LTV_RECALCULATED',
  WELCOME_COUPON_ISSUED = 'WELCOME_COUPON_ISSUED',
  CROSS_SELL_OPPORTUNITY = 'CROSS_SELL_OPPORTUNITY',
}

export interface DomainEvent {
  type: DomainEventType;
  userId: string;
  payload: Record<string, unknown>;
  metadata?: {
    businessId?: string;
    businessName?: string;
    orderId?: string;
    bookingId?: string;
    paymentId?: string;
    amount?: string;
    currency?: string;
    link?: string;
    productId?: string;
    serviceId?: string;
    moduleId?: string;
    rentalId?: string;
    deliveryId?: string;
    ticketId?: string;
    employeeId?: string;
    campaignId?: string;
    promotionId?: string;
    adId?: string;
    disputeId?: string;
    debtId?: string;
    escrowId?: string;
    subscriptionId?: string;
    badgeType?: string;
    score?: number;
    previousScore?: number;
    tier?: string;
    points?: number;
    reason?: string;
    device?: string;
    location?: string;
    channel?: string;
    recipientRole?: string;
    email?: string;
    phone?: string;
  };
  timestamp: Date;
}
