import type { NavGroup } from '@/constants/index';
import {
  LayoutDashboard,
  Globe,
  Users,
  MessageCircle,
  Star,
  Bell,
  BarChart3,
  Settings,
  LifeBuoy,
  ShoppingBag,
  Hand,
  UtensilsCrossed,
  Hotel,
  CalendarCheck,
  Truck,
  Palette,
  Car,
  Calendar,
  CalendarDays,
  Megaphone,
  Clock,
  FileText,
  Wallet,
  Repeat,
  File,
  Scale,
  Briefcase,
  Wrench,
  Store,
  ChevronDown,
  ChevronLeft,
  Sparkles,
  Heart,
  Shield,
  Code,
  User,
  Compass,
  Search,
  Package,
  CreditCard,
  Award,
  Database,
  UserCheck,
  UserPlus,
  Building2,
  ShoppingCart,
  Flag,
  Lock,
  Key,
  HardDrive,
  Download,
  Upload,
  Activity,
  GraduationCap,
  MessageSquare,
  Folder,
  Image as ImageIcon,
  Beaker,
  Layers,
  Tag,
  TrendingUp,
  Gem,
  Percent,
  Bot,
  AlertTriangle,
  ShieldCheck,
  Zap,
  ClipboardList,
  Play,
  Film,
  Radio,
  Monitor,
  Ruler,
  Mic,
} from 'lucide-react';

export const iconMap: Record<string, React.ComponentType<any>> = {
  LayoutDashboard,
  Globe,
  Users,
  MessageCircle,
  Star,
  Bell,
  BarChart3,
  Settings,
  LifeBuoy,
  ShoppingBag,
  ShoppingCart,
  Hand,
  UtensilsCrossed,
  Hotel,
  CalendarCheck,
  Truck,
  Palette,
  Car,
  Calendar,
  Megaphone,
  Clock,
  FileText,
  Wallet,
  Repeat,
  File,
  Scale,
  Briefcase,
  Wrench,
  Store,
  Heart,
  Shield,
  Code,
  User,
  Compass,
  Search,
  Sparkles,
  Package,
  CreditCard,
  Award,
  Database,
  UserCheck,
  UserPlus,
  Building2,
  Flag,
  Lock,
  Key,
  HardDrive,
  Download,
  Upload,
  Activity,
  CalendarDays,
  GraduationCap,
  MessageSquare,
  Folder,
  Image: ImageIcon,
  Beaker,
  Layers,
  Tag,
  TrendingUp,
  Gem,
  Percent,
  Bot,
  AlertTriangle,
  ShieldCheck,
  Zap,
  ClipboardList,
  Play,
  Film,
  Radio,
  Monitor,
  Ruler,
  Mic,
};

export const MODULE_ICON_MAP: Record<string, string> = {
  PRODUCTS: 'ShoppingBag',
  SERVICES: 'Hand',
  MENU: 'UtensilsCrossed',
  ROOMS: 'Hotel',
  BOOKINGS: 'CalendarCheck',
  ORDERS: 'ShoppingBag',
  EVENTS: 'Calendar',
  RENTALS: 'Car',

  PORTFOLIO: 'Palette',
  TRAINING: 'GraduationCap',
  DELIVERIES: 'Truck',
  EMPLOYEES: 'Briefcase',
  PLANNING: 'Clock',
  QUOTES_INVOICES: 'FileText',
  DEBTS_PAYMENTS: 'Wallet',
  SUBSCRIPTIONS: 'Repeat',
  DOCUMENTS: 'File',
  PARTNERS: 'Users',
  DISPUTES: 'Scale',
  MODULE_MARKETPLACE: 'Store',
  ADVANCED_TASKS: 'Wrench',
};

export const MODULE_LABEL_MAP: Record<string, string> = {
  PRODUCTS: 'Produits',
  SERVICES: 'Services',
  MENU: 'Menu / Carte',
  ROOMS: 'Chambres',
  BOOKINGS: 'Réservations',
  ORDERS: 'Commandes',
  EVENTS: 'Événements',
  RENTALS: 'Locations',

  PORTFOLIO: 'Portfolio',
  DELIVERIES: 'Livraisons',
  EMPLOYEES: 'Employés',
  PLANNING: 'Planning',
  QUOTES_INVOICES: 'Devis & Factures',
  DEBTS_PAYMENTS: 'Créances',
  SUBSCRIPTIONS: 'Abonnements',
  TRAINING: 'Formations',
  DOCUMENTS: 'Documents',
  PARTNERS: 'Partenaires',
  DISPUTES: 'Litiges',
  MODULE_MARKETPLACE: 'Marketplace',
  ADVANCED_TASKS: 'Tâches avancées',
};

export const MODULE_HREF_MAP: Record<string, string> = {
  QUOTES_INVOICES: '/dashboard/quotes',
  DEBTS_PAYMENTS: '/dashboard/debts-payments',
  MODULE_MARKETPLACE: '/dashboard/marketplace',
  ADVANCED_TASKS: '/dashboard/tasks',
  DOCUMENTS: '/dashboard/documents',
  DISPUTES: '/dashboard/disputes',
  TRAINING: '/dashboard/trainings/manage',
  ORDERS: '/dashboard/business/orders',
  BOOKINGS: '/dashboard/bookings/calendar',
};

export const DEVELOPER_NAV_GROUPS = [
  {
    label: 'Général',
    key: 'dev_general',
    items: [{ label: 'Tableau de bord', href: '/dashboard/developer', icon: 'LayoutDashboard' }],
  },
  {
    label: 'Media',
    key: 'dev_media',
    items: [
      { label: 'Media Hub', href: '/dashboard/developer/media', icon: 'Play' },
      { label: 'Stories', href: '/dashboard/developer/media/stories', icon: 'Sparkles' },
      { label: 'Shorts', href: '/dashboard/developer/media/shorts', icon: 'Film' },
      { label: 'Lives', href: '/dashboard/developer/media/lives', icon: 'Radio' },
    ],
  },
  {
    label: 'Modules',
    key: 'dev_modules',
    items: [
      { label: 'Tous les modules', href: '/dashboard/developer/modules', icon: 'Package' },
      { label: 'Créer un module', href: '/dashboard/developer/modules/publish', icon: 'Sparkles' },
      { label: 'Versions & Releases', href: '/dashboard/developer/versions', icon: 'Repeat' },
    ],
  },
  {
    label: 'Marketplace',
    key: 'dev_marketplace',
    items: [
      { label: 'Marketplace', href: '/dashboard/developer/marketplace', icon: 'Store' },
      { label: 'Validation AfriBiz', href: '/dashboard/developer/validation', icon: 'Shield' },
    ],
  },
  {
    label: 'Revenus',
    key: 'dev_revenues',
    items: [
      { label: "Vue d'ensemble", href: '/dashboard/developer/revenues', icon: 'Wallet' },
      { label: 'Ventes', href: '/dashboard/developer/revenues/sales', icon: 'ShoppingBag' },
      {
        label: 'Abonnements',
        href: '/dashboard/developer/revenues/subscriptions',
        icon: 'CreditCard',
      },
      { label: 'Retraits', href: '/dashboard/developer/revenues/payouts', icon: 'Download' },
      { label: 'Factures', href: '/dashboard/developer/revenues/invoices', icon: 'FileText' },
    ],
  },
  {
    label: 'Clients',
    key: 'dev_clients',
    items: [
      { label: 'Installations', href: '/dashboard/developer/installations', icon: 'Download' },
      { label: 'Clients', href: '/dashboard/developer/clients', icon: 'Users' },
    ],
  },
  {
    label: 'Communication',
    key: 'dev_communication',
    items: [
      { label: 'Messages', href: '/dashboard/developer/messages', icon: 'MessageCircle' },
      { label: 'Support', href: '/dashboard/developer/support', icon: 'LifeBuoy' },
      { label: 'Avis & Notes', href: '/dashboard/developer/reviews', icon: 'Star' },
    ],
  },
  {
    label: 'Analyse',
    key: 'dev_analytics',
    items: [
      { label: 'Analytics', href: '/dashboard/developer/analytics', icon: 'BarChart3' },
      { label: 'Performance', href: '/dashboard/developer/performance', icon: 'Activity' },
    ],
  },
  {
    label: 'Marketing',
    key: 'dev_marketing',
    items: [{ label: 'Marketing', href: '/dashboard/developer/marketing', icon: 'Megaphone' }],
  },
  {
    label: 'Documentation',
    key: 'dev_docs',
    items: [
      { label: 'Documentation', href: '/dashboard/developer/documentation', icon: 'FileText' },
      { label: 'Communauté', href: '/dashboard/developer/community', icon: 'MessageCircle' },
    ],
  },
  {
    label: 'Développeur',
    key: 'dev_developer',
    items: [
      { label: 'Mon abonnement', href: '/dashboard/developer/subscription', icon: 'CreditCard' },
      { label: 'API & Intégrations', href: '/dashboard/developer/api', icon: 'Key' },
      { label: 'Sécurité', href: '/dashboard/developer/security', icon: 'Lock' },
      { label: 'Profil', href: '/dashboard/developer/profile', icon: 'User' },
      { label: 'Paramètres', href: '/dashboard/developer/settings', icon: 'Settings' },
    ],
  },
  {
    label: 'Simulation',
    key: 'dev_simulation',
    items: [{ label: 'Sandbox', href: '/dashboard/developer/simulation', icon: 'Beaker' }],
  },
];

export const BUSINESS_CORE_NAV: NavGroup[] = [
  {
    label: 'Général',
    items: [
      { label: 'Tableau de bord', href: '/dashboard/business', icon: 'LayoutDashboard' },
      { label: 'Page publique', href: '/dashboard/public-page', icon: 'Globe' },
      { label: 'Mes modules', href: '/dashboard/business/modules', icon: 'Package' },
    ],
  },
  {
    label: 'Social Commerce',
    items: [
      { label: 'Explorer', href: '/dashboard/explore', icon: 'Compass' },
      { label: 'Media Commerce', href: '/dashboard/media-commerce', icon: 'Film' },
      { label: 'Stories', href: '/dashboard/stories', icon: 'Sparkles' },
      { label: 'Shorts', href: '/dashboard/shorts', icon: 'Film' },
      { label: 'Lives', href: '/dashboard/lives', icon: 'Radio' },
    ],
  },
  {
    label: 'CRM & Relation Client',
    items: [
      { label: 'Clients', href: '/dashboard/clients', icon: 'Users' },
      { label: 'Segments', href: '/dashboard/clients/segments', icon: 'Layers' },
      { label: 'Analytics CRM', href: '/dashboard/clients/analytics', icon: 'BarChart3' },
      { label: 'Intelligence client', href: '/dashboard/client-intelligence', icon: 'Bot' },
      { label: 'Commentaires', href: '/dashboard/comments', icon: 'MessageSquare' },
      { label: 'Signalements', href: '/dashboard/content-reports', icon: 'Flag' },
      { label: 'Messagerie', href: '/dashboard/business/messages', icon: 'MessageCircle' },
      { label: 'Avis', href: '/dashboard/reviews', icon: 'Star' },
      { label: 'Pipeline CRM', href: '/dashboard/crm/pipeline', icon: 'ClipboardList' },
      { label: 'Automation CRM', href: '/dashboard/crm/automation', icon: 'Zap' },
    ],
  },
  {
    label: 'Marketing & Croissance',
    items: [
      { label: 'Campagnes', href: '/dashboard/marketing', icon: 'Megaphone' },
      { label: 'Promotions', href: '/dashboard/promotions', icon: 'Sparkles' },
      { label: 'Offres Flash', href: '/dashboard/offers', icon: 'Zap' },
      { label: 'Coupons', href: '/dashboard/promotions/coupons', icon: 'Tag' },
      { label: 'Bundles', href: '/dashboard/promotions/bundles', icon: 'Package' },
      { label: 'Fidélité', href: '/dashboard/promotions/loyalty', icon: 'Award' },
      { label: 'Stats Promos', href: '/dashboard/promotions/stats', icon: 'BarChart3' },
      { label: 'Réseaux sociaux', href: '/dashboard/social-accounts', icon: 'Globe' },
      { label: 'Publicités', href: '/dashboard/ads', icon: 'Megaphone' },
      { label: 'Attention', href: '/dashboard/attention', icon: 'AlertTriangle' },
      { label: 'Achat Groupé', href: '/dashboard/group-buys', icon: 'ShoppingCart' },
      { label: 'Growth Engine', href: '/dashboard/growth-engine', icon: 'TrendingUp' },
      { label: 'Growth Coaching', href: '/dashboard/growth-coaching', icon: 'UserCheck' },
      { label: 'Badges & Succès', href: '/dashboard/gamification', icon: 'Award' },
      { label: 'Statistiques', href: '/dashboard/statistics', icon: 'BarChart3' },
      { label: 'AfriScore', href: '/dashboard/afriscore', icon: 'Award' },
      { label: 'Défis & Quêtes', href: '/dashboard/afriscore/gamification', icon: 'Trophy' },
    ],
  },
  {
    label: 'Wallet Business',
    items: [
      { label: 'Portefeuille', href: '/dashboard/wallet', icon: 'Wallet' },
      { label: 'Transactions', href: '/dashboard/payments/transactions', icon: 'CreditCard' },
      { label: 'Paiements', href: '/dashboard/payments', icon: 'CreditCard' },
      { label: 'Escrow', href: '/dashboard/escrow', icon: 'Shield' },
      { label: 'Comptabilité', href: '/dashboard/accounting', icon: 'BarChart3' },
      { label: 'Tontine & Épargne', href: '/dashboard/savings', icon: 'Wallet' },
      { label: 'Réseau Agents', href: '/dashboard/agents', icon: 'Users' },
    ],
  },
  {
    label: 'Configuration',
    items: [
      { label: 'Alertes', href: '/dashboard/alerts', icon: 'Bell' },
      { label: 'Signature électronique', href: '/dashboard/signatures', icon: 'FileText' },
      { label: 'Paiements hybrides', href: '/dashboard/hybrid-payments', icon: 'CreditCard' },
      { label: 'Consentements', href: '/dashboard/consents', icon: 'Shield' },
      { label: 'Automatisations', href: '/dashboard/automations', icon: 'Activity' },
      {
        label: 'Notifications client',
        href: '/dashboard/business/notification-templates',
        icon: 'Bell',
      },
      { label: 'Taxes ZLECAF', href: '/dashboard/taxes', icon: 'FileText' },
      { label: 'Unités de mesure', href: '/dashboard/units', icon: 'Ruler' },
      { label: 'Catalogue Vocal', href: '/dashboard/voice', icon: 'Mic' },
      { label: 'Mode Hors-ligne', href: '/dashboard/offline-sync', icon: 'Download' },
      { label: 'Paramètres', href: '/dashboard/business/settings', icon: 'Settings' },
      { label: 'Support', href: '/dashboard/support', icon: 'LifeBuoy' },
    ],
  },
  {
    label: 'Data Hub',
    items: [{ label: 'Explorer', href: '/dashboard/datahub', icon: 'Database' }],
  },
];

export const MODULE_SUB_ITEMS: Record<string, { label: string; href: string; icon: string }[]> = {
  Produits: [
    { label: 'Catégories', href: '/dashboard/products/categories', icon: 'Folder' },
    { label: 'Stock', href: '/dashboard/products/stock-alerts', icon: 'AlertTriangle' },
    { label: 'Import', href: '/dashboard/products/import', icon: 'Upload' },
  ],
  Services: [{ label: 'Catégories', href: '/dashboard/services/categories', icon: 'Folder' }],
  ['Menu / Carte']: [
    { label: 'Catégories', href: '/dashboard/menu/categories', icon: 'Folder' },
    { label: 'Commandes', href: '/dashboard/menu/orders', icon: 'ShoppingBag' },
    { label: 'Tables', href: '/dashboard/menu/tables', icon: 'Layers' },
    { label: 'QR Menu', href: '/dashboard/menu/qr-menu', icon: 'Tag' },
    { label: 'Ingrédients', href: '/dashboard/menu/ingredients', icon: 'Beaker' },
  ],
  Chambres: [{ label: 'Planning', href: '/dashboard/rooms/planning', icon: 'CalendarDays' }],
  Réservations: [
    { label: 'Calendrier', href: '/dashboard/bookings/calendar', icon: 'CalendarDays' },
    { label: 'Créneaux', href: '/dashboard/bookings/slots', icon: 'Clock' },
    { label: 'Ressources', href: '/dashboard/bookings/resources', icon: 'Package' },
    { label: 'Rappels', href: '/dashboard/bookings/reminders', icon: 'Bell' },
    { label: 'Stats', href: '/dashboard/bookings/stats', icon: 'BarChart3' },
  ],
  Commandes: [
    { label: 'Stats', href: '/dashboard/orders/stats', icon: 'BarChart3' },
    { label: 'Dettes', href: '/dashboard/orders/debts', icon: 'Wallet' },
  ],
  Événements: [],
  Locations: [],
  Portfolio: [
    { label: 'Témoignages', href: '/dashboard/portfolio/testimonials', icon: 'MessageSquare' },
    { label: 'Catégories', href: '/dashboard/portfolio/categories', icon: 'Folder' },
    { label: 'Média', href: '/dashboard/portfolio/media', icon: 'Image' },
    { label: 'Stats', href: '/dashboard/portfolio/stats', icon: 'BarChart3' },
  ],
  ['Devis & Factures']: [
    { label: 'Nouveau devis', href: '/dashboard/quotes/new', icon: 'FileText' },
  ],
  Créances: [
    { label: 'Aging', href: '/dashboard/debts-payments/aging', icon: 'Clock' },
    { label: 'Rappels', href: '/dashboard/debts-payments/reminders', icon: 'Bell' },
    { label: 'Risques', href: '/dashboard/debts-payments/risks', icon: 'AlertTriangle' },
  ],
  Abonnements: [
    { label: 'Mon abonnement', href: '/dashboard/business/subscription', icon: 'CreditCard' },
    { label: 'Abonnés', href: '/dashboard/subscriptions/subscribers', icon: 'Users' },
    { label: 'Paiements', href: '/dashboard/subscriptions/payments', icon: 'CreditCard' },
    { label: 'Stats', href: '/dashboard/subscriptions/stats', icon: 'BarChart3' },
    { label: 'Activités', href: '/dashboard/subscriptions/logs', icon: 'Activity' },
  ],
  Livraisons: [
    { label: 'Zones de livraison', href: '/dashboard/deliveries/zones', icon: 'Globe' },
    { label: 'Livreurs', href: '/dashboard/deliveries/drivers', icon: 'User' },
    { label: 'Stats', href: '/dashboard/deliveries/stats', icon: 'BarChart3' },
  ],
  ['Employés']: [
    { label: 'Rôles', href: '/dashboard/employees/roles', icon: 'Shield' },
    { label: 'Pointage', href: '/dashboard/employees/attendances', icon: 'CalendarCheck' },
    { label: 'Performance', href: '/dashboard/employees/performance', icon: 'TrendingUp' },
    { label: 'Documents', href: '/dashboard/employees/documents', icon: 'File' },
    { label: 'Stats', href: '/dashboard/employees/stats', icon: 'BarChart3' },
    { label: 'Activités', href: '/dashboard/employees/activities', icon: 'Activity' },
    { label: 'Portail', href: '/dashboard/employees/portal', icon: 'User' },
    { label: 'Congés', href: '/dashboard/employees/leaves', icon: 'Calendar' },
    { label: 'Paie', href: '/dashboard/employees/payroll', icon: 'Wallet' },
  ],
  Planning: [
    { label: 'Calendrier', href: '/dashboard/planning/calendar', icon: 'CalendarDays' },
    { label: 'Schedule', href: '/dashboard/planning/schedules', icon: 'Clock' },
    { label: 'Stats', href: '/dashboard/planning/stats', icon: 'BarChart3' },
  ],
  Formations: [
    { label: 'Gérer', href: '/dashboard/trainings/manage', icon: 'Settings' },
    { label: 'Leçons', href: '/dashboard/trainings/lessons', icon: 'File' },
  ],
  Documents: [{ label: 'Signatures', href: '/dashboard/documents/signatures', icon: 'FileText' }],
  Partenaires: [
    { label: 'Contrats', href: '/dashboard/partners/contracts', icon: 'FileText' },
    { label: 'Transactions', href: '/dashboard/partners/transactions', icon: 'CreditCard' },
  ],
  Litiges: [],
  Marketplace: [],
  ['Tâches avancées']: [],
};
