-- AlterTable
ALTER TABLE "AdSlot" ADD COLUMN     "description" TEXT,
ADD COLUMN     "price1Day" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "price7Days" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "price30Days" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "maxPerSlot" INTEGER NOT NULL DEFAULT 10;
