import type { BusinessModule } from '../types/business';

export const MODULE_LABELS: Record<BusinessModule, string> = {
  PRODUCTS: 'Produits',
  SERVICES: 'Services',
  MENU: 'Menu / Carte',
  ROOMS: 'Chambres / Hébergement',
  BOOKINGS: 'Réservations',
  ORDERS: 'Commandes',
  QUOTES_INVOICES: 'Devis & Factures',
  DEBTS_PAYMENTS: 'Dettes & Paiements',
  PROMOTIONS: 'Promotions',
  PLANNING: 'Planning',
  EMPLOYEES: 'Employés',
  PORTFOLIO: 'Portfolio',
  SUBSCRIPTIONS: 'Abonnements',
  DELIVERIES: 'Livraisons',
  EVENTS: 'Événements',
  RENTALS: 'Locations',
  DOCUMENTS: 'Documents',
  PARTNERS: 'Partenaires',
  DISPUTES: 'Litiges',
  MODULE_MARKETPLACE: 'Marketplace',
  ADVANCED_TASKS: 'Tâches avancées',
  TRAINING: 'Formations',
};

export const MODULE_ICONS: Record<BusinessModule, string> = {
  PRODUCTS: 'package',
  SERVICES: 'wrench',
  MENU: 'book-open',
  ROOMS: 'bed',
  BOOKINGS: 'calendar-check',
  ORDERS: 'shopping-cart',
  QUOTES_INVOICES: 'file-text',
  DEBTS_PAYMENTS: 'credit-card',
  PROMOTIONS: 'percent',
  PLANNING: 'clock',
  EMPLOYEES: 'users',
  PORTFOLIO: 'briefcase',
  SUBSCRIPTIONS: 'repeat',
  DELIVERIES: 'truck',
  EVENTS: 'calendar',
  RENTALS: 'key',
  DOCUMENTS: 'folder',
  PARTNERS: 'handshake',
  DISPUTES: 'alert-triangle',
  MODULE_MARKETPLACE: 'globe',
  ADVANCED_TASKS: 'layers',
  TRAINING: 'graduation-cap',
};

export const MODULE_ROUTES: Record<BusinessModule, string> = {
  PRODUCTS: 'products',
  SERVICES: 'services',
  MENU: 'menu',
  ROOMS: 'rooms',
  BOOKINGS: 'bookings',
  ORDERS: 'orders',
  QUOTES_INVOICES: 'quotes',
  DEBTS_PAYMENTS: 'debts',
  PROMOTIONS: 'promotions',
  PLANNING: 'planning',
  EMPLOYEES: 'employees',
  PORTFOLIO: 'portfolio',
  SUBSCRIPTIONS: 'subscriptions',
  DELIVERIES: 'deliveries',
  EVENTS: 'events',
  RENTALS: 'rentals',
  DOCUMENTS: 'documents',
  PARTNERS: 'partners',
  DISPUTES: 'disputes',
  MODULE_MARKETPLACE: 'marketplace',
  ADVANCED_TASKS: 'advanced-tasks',
  TRAINING: 'training',
};
