export interface ApiSearchItem {
  _type?: string;
  type?: string;
  id: string;
  name?: string;
  title?: string;
  slug?: string;
  rating?: number;
  reviewCount?: number;
  city?: string;
  country?: string;
  logo?: string;
  image?: string;
  images?: string[];
  category?: string;
  shortDescription?: string;
  description?: string;
  isVerified?: boolean;
  isPremium?: boolean;
  isTopSeller?: boolean;
  isRecommended?: boolean;
  modules?: string[];
  price?: number | string;
  promotionalPrice?: number | string;
  stock?: number;
  isAvailable?: boolean;
  isActive?: boolean;
  duration?: string;
  lessons?: number;
  latitude?: number;
  longitude?: number;
  distanceFormatted?: string;
  business?: {
    id?: string;
    name?: string;
    slug?: string;
    city?: string;
    country?: string;
  };
  startDate?: string;
  address?: string;
  capacity?: number;
  remainingSpots?: number;
  deposit?: number;
  companyName?: string;
  skills?: string[];
  _moduleCount?: number;
  coverImage?: string;
  afriScore?: number;
  developer?: { companyName?: string };
  version?: string;
  totalInstalls?: number;
  user?: { firstName?: string; lastName?: string };
  badges?: string[];
  distance?: string;
  businessSlug?: string;
  reviews?: {
    id: string;
    rating: number;
    comment?: string;
    createdAt?: string;
    user?: { firstName?: string; lastName?: string };
  }[];
}
