apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: afribiz
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: frontend
