import { PrismaClient } from '@prisma/client';

function createMockPrisma(): Record<string, any> {
  const makeModel = (methods: string[] = ['create', 'findFirst', 'findUnique', 'findMany', 'update', 'updateMany', 'delete', 'deleteMany', 'count', 'aggregate', 'groupBy']) => {
    const obj: Record<string, jest.Mock> = {};
    for (const m of methods) {
      obj[m] = jest.fn();
    }
    return obj;
  };

  const mock: Record<string, any> = {
    user: makeModel(),
    session: makeModel(),
    refreshToken: makeModel(),
    emailVerification: makeModel(['create', 'findFirst', 'update']),
    passwordReset: makeModel(['create', 'findFirst', 'update']),
    otpCode: makeModel(['create', 'findFirst', 'findMany', 'update', 'delete']),
    securityLog: makeModel(['create', 'findMany']),
    device: makeModel(),
    notification: makeModel(),
    notificationDelivery: makeModel(),
    notificationPreference: makeModel(),
    business: makeModel(),
    businessSettings: makeModel(),
    businessHour: makeModel(),
    businessPaymentMethod: makeModel(),
    service: makeModel(),
    serviceCategory: makeModel(),
    serviceEmployee: makeModel(),
    menuCategory: makeModel(),
    menuItem: makeModel(),
    menuItemVariant: makeModel(),
    ingredient: makeModel(),
    restaurantTable: makeModel(),
    menuOrder: makeModel(),
    productCategory: makeModel(),
    product: makeModel(),
    productVariant: makeModel(),
    paymentTransaction: makeModel(),
    cart: makeModel(),
    cartItem: makeModel(),
    order: makeModel(),
    orderItem: makeModel(),
    booking: makeModel(),
    bookingResource: makeModel(),
    timeSlot: makeModel(),
    bookingReminder: makeModel(),
    expense: makeModel(),
    room: makeModel(),
    event: makeModel(),
    eventTicket: makeModel(),
    eventParticipant: makeModel(),
    eventScan: makeModel(),
    eventPromotion: makeModel(),
    eventGallery: makeModel(),
    eventPartner: makeModel(),
    rental: makeModel(),
    partner: makeModel(),
    businessReview: makeModel(),
    review: makeModel(),
    conversation: makeModel(),
    message: makeModel(),
    favorite: makeModel(),
    quote: makeModel(),
    quoteItem: makeModel(),
    invoice: makeModel(),
    invoiceItem: makeModel(),
    payment: makeModel(),
    paymentProof: makeModel(),
    debt: makeModel(),
    escrow: makeModel(),
    clientRisk: makeModel(),
    businessClient: makeModel(),
    businessTag: makeModel(),
    businessClientTag: makeModel(),
    clientNote: makeModel(),
    clientSegment: makeModel(),
    segmentClient: makeModel(),
    debtReminder: makeModel(),
    financialLog: makeModel(),
    planningTask: makeModel(),
    employeeSchedule: makeModel(),
    planningLog: makeModel(),
    employee: makeModel(),
    employeeRole: makeModel(),
    attendance: makeModel(),
    employeeDocument: makeModel(),
    employeePerformance: makeModel(),
    employeeActivity: makeModel(),
    promotion: makeModel(),
    coupon: makeModel(),
    bundle: makeModel(),
    bundleItem: makeModel(),
    marketingCampaign: makeModel(),
    promotionLog: makeModel(),
    loyaltyProgram: makeModel(),
    loyaltyPoints: makeModel(),
    loyaltyTransaction: makeModel(),
    referral: makeModel(),
    referralReward: makeModel(),
    portfolioCategory: makeModel(),
    portfolioItem: makeModel(),
    portfolioMedia: makeModel(),
    portfolioInteraction: makeModel(),
    portfolioTestimonial: makeModel(),
    subscriptionPlan: makeModel(),
    subscriptionPrivilege: makeModel(),
    businessSubscription: makeModel(),
    subscriptionPayment: makeModel(),
    subscriptionLog: makeModel(),
    driver: makeModel(),
    delivery: makeModel(),
    deliveryTracking: makeModel(),
    deliveryProof: makeModel(),
    adPackage: makeModel(),
    adCampaign: makeModel(),
    adCreative: makeModel(),
    adImpression: makeModel(),
    adClick: makeModel(),
    adConversion: makeModel(),
    adInvoice: makeModel(),
    businessScore: makeModel(),
    scoreHistory: makeModel(),
    businessBadge: makeModel(),
    dataConsent: makeModel(),
    dataPartner: makeModel(),
    partnerSubscription: makeModel(),
    dataReport: makeModel(),
    dataAccessLog: makeModel(),
    sectorBenchmark: makeModel(),
    developerProfile: makeModel(),
    developerModule: makeModel(),
    developerModuleVersion: makeModel(),
    developerModuleInstallation: makeModel(),
    developerModuleReview: makeModel(),
    developerSupportTicket: makeModel(),
    developerSupportMessage: makeModel(),
    developerRevenue: makeModel(),
    developerPayout: makeModel(),
    developerApiKey: makeModel(['create', 'findMany', 'update', 'delete']),
    modulePermission: makeModel(),
    moduleConfiguration: makeModel(),
    moduleActivityLog: makeModel(['create', 'findMany', 'count', 'groupBy']),
    moduleValidation: makeModel(['create', 'findFirst']),
    moduleLicense: makeModel(['create', 'findFirst']),
    training: makeModel(),
    trainingLesson: makeModel(),
    trainingQuiz: makeModel(),
    quizQuestion: makeModel(),
    userQuizAttempt: makeModel(),
    userTraining: makeModel(),
    taskCategory: makeModel(),
    taskChecklist: makeModel(),
    taskComment: makeModel(),
    taskTimer: makeModel(),
    taskResource: makeModel(),
    taskValidation: makeModel(),
    partnerContract: makeModel(),
    partnerTransaction: makeModel(),
    partnerAssignment: makeModel(),
    partnerReview: makeModel(),
    partnerDocument: makeModel(),
    partnerPermission: makeModel(),
    businessDocument: makeModel(),
    documentSignature: makeModel(),
    dispute: makeModel(),
    queuedEvent: makeModel(),
    moduleManifest: makeModel(),
    developerBadge: makeModel(),
    moduleCommission: makeModel(),
    $connect: jest.fn(),
    $disconnect: jest.fn(),
  };
  (mock as any).$transaction = jest.fn((fn: (mockPrisma: any) => Promise<any>) => fn(mock));
  return mock;
}

const mockPrisma = createMockPrisma();

jest.mock('@/lib/db', () => ({
  prisma: mockPrisma,
}));

jest.mock('@/lib/logger', () => ({
  logger: {
    info: jest.fn(),
    error: jest.fn(),
    warn: jest.fn(),
    debug: jest.fn(),
  },
}));

jest.mock('@/lib/mail', () => ({
  sendEmail: jest.fn().mockResolvedValue(undefined),
  emailTemplates: {
    welcome: jest.fn().mockReturnValue({ subject: 'Welcome', html: '<html></html>' }),
    passwordReset: jest.fn().mockReturnValue({ subject: 'Reset', html: '<html></html>' }),
    otp: jest.fn().mockReturnValue({ subject: 'OTP', html: '<html></html>' }),
  },
}));

jest.mock('@/services/twoFactorService', () => ({
  generateSecret: jest.fn().mockResolvedValue({ secret: 'mock-secret', uri: 'otpauth://...' }),
  verifyToken: jest.fn().mockResolvedValue(true),
  generateQrCode: jest.fn().mockResolvedValue('data:image/png;base64,...'),
}));

export { mockPrisma };
