import {
  ShoppingBag, Scissors, UtensilsCrossed, Hotel, Shirt, Smartphone,
  Stethoscope, BookOpen, GraduationCap, Hammer, Truck, CalendarCheck,
  Building2, Palette, Hand, Store, Wrench, Car, Tractor,
  Warehouse, Globe, Megaphone, Camera, FileText, Wallet, type LucideIcon,
} from 'lucide-react';

export const BUSINESS_TYPE_LABELS: Record<string, string> = {
  RESTAURANT: 'Restaurant',
  FAST_FOOD: 'Fast-food / Snack',
  PATISSERIE: 'Pâtisserie',
  BOULANGERIE: 'Boulangerie',
  CAFE: 'Café / Salon de thé',
  BAR: 'Bar / Night-club',
  HOTEL: 'Hôtel',
  AUBERGE: 'Auberge',
  MAISON_D_HOTES: 'Maison d\'hôtes',
  LOCATION_SAISONNIERE: 'Location saisonnière',
  BOUTIQUE_VETEMENTS: 'Boutique de vêtements',
  BOUTIQUE_CHAUSSURES: 'Boutique de chaussures',
  BOUTIQUE_COSMETIQUES: 'Boutique de cosmétiques',
  BOUTIQUE_INFORMATIQUE: 'Boutique informatique',
  BOUTIQUE_TELEPHONIQUE: 'Boutique téléphonique',
  BOUTIQUE_ELECTRONIQUE: 'Boutique électronique',
  SUPERMARCHE: 'Supermarché',
  EPICERIE: 'Épicerie',
  PHARMACIE: 'Pharmacie',
  LIBRAIRIE: 'Librairie',
  PAPETERIE: 'Papeterie',
  SALON_COIFFURE: 'Salon de coiffure',
  SALON_BEAUTE: 'Salon de beauté',
  SPA: 'SPA / Bien-être',
  INSTITUT_ESTHETIQUE: 'Institut esthétique',
  PHOTOGRAPHE: 'Photographe',
  VIDEOASTE: 'Vidéaste',
  AGENCE_MARKETING: 'Agence marketing',
  AGENCE_COMMUNICATION: 'Agence de communication',
  AGENCE_DIGITALE: 'Agence digitale',
  AGENCE_IMMOBILIERE: 'Agence immobilière',
  CABINET_JURIDIQUE: 'Cabinet juridique',
  CABINET_COMPTABLE: 'Cabinet comptable',
  CABINET_CONSEIL: 'Cabinet de conseil',
  CABINET_MEDICAL: 'Cabinet médical',
  CLINIQUE: 'Clinique',
  CENTRE_FORMATION: 'Centre de formation',
  ECOLE_PRIVEE: 'École privée',
  FREELANCE: 'Freelance',
  DEVELOPPEUR: 'Développeur',
  DESIGNER_GRAPHIQUE: 'Designer graphique',
  CONSULTANT: 'Consultant',
  COACH_PROFESSIONNEL: 'Coach professionnel',
  ARTISAN: 'Artisan',
  MENUISIER: 'Menuisier',
  MACON: 'Maçon',
  PLOMBIER: 'Plombier',
  ELECTRICIEN: 'Électricien',
  SOUDEUR: 'Soudeur',
  MECANICIEN: 'Mécanicien',
  ENTREPRISE_AGRICOLE: 'Entreprise agricole',
  ELEVAGE: 'Élevage',
  TRANSPORT: 'Transport',
  LIVRAISON: 'Livraison / Course',
  ORGANISATION_EVENEMENTS: 'Organisation d\'événements',
  LOCATION_VEHICULES: 'Location de véhicules',
  LOCATION_EQUIPEMENTS: 'Location d\'équipements',
  LOCATION_ENGINS: 'Location d\'engins',
  IMPORT_EXPORT: 'Import / Export',
  ASSOCIATION: 'Association',
  ONG: 'ONG',
  ENTREPRISE_PRIVEE: 'Entreprise privée',
  AUTRE: 'Autre',
};

export const BUSINESS_TYPE_ICONS: Record<string, LucideIcon> = {
  RESTAURANT: UtensilsCrossed,
  FAST_FOOD: UtensilsCrossed,
  PATISSERIE: UtensilsCrossed,
  BOULANGERIE: UtensilsCrossed,
  CAFE: UtensilsCrossed,
  BAR: UtensilsCrossed,
  HOTEL: Hotel,
  AUBERGE: Hotel,
  MAISON_D_HOTES: Hotel,
  LOCATION_SAISONNIERE: Hotel,
  BOUTIQUE_VETEMENTS: Shirt,
  BOUTIQUE_CHAUSSURES: Shirt,
  BOUTIQUE_COSMETIQUES: Palette,
  BOUTIQUE_INFORMATIQUE: Smartphone,
  BOUTIQUE_TELEPHONIQUE: Smartphone,
  BOUTIQUE_ELECTRONIQUE: Smartphone,
  SUPERMARCHE: Store,
  EPICERIE: Store,
  PHARMACIE: Stethoscope,
  LIBRAIRIE: BookOpen,
  PAPETERIE: BookOpen,
  SALON_COIFFURE: Scissors,
  SALON_BEAUTE: Scissors,
  SPA: Scissors,
  INSTITUT_ESTHETIQUE: Scissors,
  PHOTOGRAPHE: Camera,
  VIDEOASTE: Camera,
  AGENCE_MARKETING: Megaphone,
  AGENCE_COMMUNICATION: Megaphone,
  AGENCE_DIGITALE: Globe,
  AGENCE_IMMOBILIERE: Building2,
  CABINET_JURIDIQUE: Building2,
  CABINET_COMPTABLE: Building2,
  CABINET_CONSEIL: Building2,
  CABINET_MEDICAL: Stethoscope,
  CLINIQUE: Stethoscope,
  CENTRE_FORMATION: GraduationCap,
  ECOLE_PRIVEE: GraduationCap,
  FREELANCE: Globe,
  DEVELOPPEUR: Smartphone,
  DESIGNER_GRAPHIQUE: Palette,
  CONSULTANT: Hand,
  COACH_PROFESSIONNEL: Hand,
  ARTISAN: Hammer,
  MENUISIER: Hammer,
  MACON: Hammer,
  PLOMBIER: Wrench,
  ELECTRICIEN: Wrench,
  SOUDEUR: Wrench,
  MECANICIEN: Car,
  ENTREPRISE_AGRICOLE: Tractor,
  ELEVAGE: Tractor,
  TRANSPORT: Truck,
  LIVRAISON: Truck,
  ORGANISATION_EVENEMENTS: CalendarCheck,
  LOCATION_VEHICULES: Car,
  LOCATION_EQUIPEMENTS: Warehouse,
  LOCATION_ENGINS: Warehouse,
  IMPORT_EXPORT: Globe,
  ASSOCIATION: Hand,
  ONG: Hand,
  ENTREPRISE_PRIVEE: Building2,
  AUTRE: Building2,
};

export const BUSINESS_CATEGORIES = [
  {
    label: 'Restauration & Hôtellerie',
    types: ['RESTAURANT', 'FAST_FOOD', 'PATISSERIE', 'BOULANGERIE', 'CAFE', 'BAR', 'HOTEL', 'AUBERGE', 'MAISON_D_HOTES', 'LOCATION_SAISONNIERE'],
  },
  {
    label: 'Commerce & Magasins',
    types: ['BOUTIQUE_VETEMENTS', 'BOUTIQUE_CHAUSSURES', 'BOUTIQUE_COSMETIQUES', 'BOUTIQUE_INFORMATIQUE', 'BOUTIQUE_TELEPHONIQUE', 'BOUTIQUE_ELECTRONIQUE', 'SUPERMARCHE', 'EPICERIE', 'PHARMACIE', 'LIBRAIRIE', 'PAPETERIE'],
  },
  {
    label: 'Beauté & Bien-être',
    types: ['SALON_COIFFURE', 'SALON_BEAUTE', 'SPA', 'INSTITUT_ESTHETIQUE'],
  },
  {
    label: 'Création & Médias',
    types: ['PHOTOGRAPHE', 'VIDEOASTE', 'AGENCE_MARKETING', 'AGENCE_COMMUNICATION', 'AGENCE_DIGITALE', 'DESIGNER_GRAPHIQUE'],
  },
  {
    label: 'Services professionnels',
    types: ['AGENCE_IMMOBILIERE', 'CABINET_JURIDIQUE', 'CABINET_COMPTABLE', 'CABINET_CONSEIL', 'CABINET_MEDICAL', 'CLINIQUE', 'CENTRE_FORMATION', 'ECOLE_PRIVEE'],
  },
  {
    label: 'Freelance & Consulting',
    types: ['FREELANCE', 'DEVELOPPEUR', 'CONSULTANT', 'COACH_PROFESSIONNEL'],
  },
  {
    label: 'Artisanat & Métiers',
    types: ['ARTISAN', 'MENUISIER', 'MACON', 'PLOMBIER', 'ELECTRICIEN', 'SOUDEUR', 'MECANICIEN'],
  },
  {
    label: 'Agriculture & Transport',
    types: ['ENTREPRISE_AGRICOLE', 'ELEVAGE', 'TRANSPORT', 'LIVRAISON'],
  },
  {
    label: 'Services spécialisés',
    types: ['ORGANISATION_EVENEMENTS', 'LOCATION_VEHICULES', 'LOCATION_EQUIPEMENTS', 'LOCATION_ENGINS', 'IMPORT_EXPORT'],
  },
  {
    label: 'Autres',
    types: ['ASSOCIATION', 'ONG', 'ENTREPRISE_PRIVEE', 'AUTRE'],
  },
];

export interface ModuleDef {
  key: string;
  label: string;
  description: string;
  icon: LucideIcon;
  color: string;
}

export const BUSINESS_MODULES: ModuleDef[] = [
  { key: 'PRODUCTS', label: 'Produits', description: 'Gérer un catalogue de produits avec stock, prix, images et catégories.', icon: ShoppingBag, color: 'emerald' },
  { key: 'SERVICES', label: 'Services', description: 'Proposer des services avec tarifs, durée et disponibilité.', icon: Hand, color: 'blue' },
  { key: 'MENU', label: 'Menu / Carte', description: 'Créer un menu ou une carte avec catégories, prix et ingrédients.', icon: UtensilsCrossed, color: 'orange' },
  { key: 'ROOMS', label: 'Chambres', description: 'Gérer des chambres ou logements avec capacités, prix et équipements.', icon: Hotel, color: 'purple' },
  { key: 'BOOKINGS', label: 'Réservations', description: 'Accepter et gérer les réservations en ligne.', icon: CalendarCheck, color: 'pink' },
  { key: 'ORDERS', label: 'Commandes', description: 'Recevoir et gérer les commandes clients en ligne.', icon: ShoppingBag, color: 'amber' },
  { key: 'EVENTS', label: 'Événements', description: 'Publier et promouvoir des événements.', icon: CalendarCheck, color: 'red' },
  { key: 'RENTALS', label: 'Locations', description: 'Gérer la location d\'équipements, véhicules ou engins.', icon: Car, color: 'cyan' },
  { key: 'PROMOTIONS', label: 'Promotions', description: 'Créer des offres promotionnelles et codes de réduction.', icon: Megaphone, color: 'rose' },
  { key: 'PORTFOLIO', label: 'Portfolio', description: 'Exposer vos réalisations et projets.', icon: Palette, color: 'indigo' },
  { key: 'DELIVERIES', label: 'Livraisons', description: 'Configurer zones et tarifs de livraison.', icon: Truck, color: 'lime' },
  { key: 'EMPLOYEES', label: 'Employés', description: 'Gérer votre équipe et leurs accès.', icon: Hand, color: 'teal' },
  { key: 'PLANNING', label: 'Planning', description: 'Planifier et organiser vos activités.', icon: CalendarCheck, color: 'violet' },
  { key: 'QUOTES_INVOICES', label: 'Devis & Factures', description: 'Générer des devis et factures professionnels.', icon: FileText, color: 'slate' },
  { key: 'DEBTS_PAYMENTS', label: 'Créances & Paiements', description: 'Suivre les paiements clients et fournisseurs.', icon: Wallet, color: 'green' },
  { key: 'SUBSCRIPTIONS', label: 'Abonnements', description: 'Proposer des formules d\'abonnement.', icon: Building2, color: 'yellow' },
  { key: 'DOCUMENTS', label: 'Documents', description: 'Centraliser vos documents administratifs.', icon: FileText, color: 'stone' },
  { key: 'PARTNERS', label: 'Partenaires', description: 'Gérer vos partenariats et collaborations.', icon: Hand, color: 'sky' },
  { key: 'DISPUTES', label: 'Litiges', description: 'Gérer les réclamations et litiges clients.', icon: Building2, color: 'red' },
  { key: 'MODULE_MARKETPLACE', label: 'Marketplace', description: 'Vendre sur la place de marché AfriBiz.', icon: Store, color: 'emerald' },
  { key: 'ADVANCED_TASKS', label: 'Tâches avancées', description: 'Automatisations et fonctionnalités avancées.', icon: Wrench, color: 'gray' },
];

export const TOGO_CITIES = [
  'Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Kpalimé', 'Bassar', 'Tsévié',
  'Aného', 'Mango', 'Dapaong', 'Tchamba', 'Niamtougou', 'Bafilo',
  'Notsé', 'Sotouboua', 'Vogan', 'Badou', 'Tabligbo', 'Kandé',
  'Amlamé', 'Pagouda', 'Kpagouda', 'Agbelouvé',
];
