import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'AfriBiz API',
      version: '1.0.0',
      description: [
        'API REST de la plateforme AfriBiz.',
        '',
        '## Fonctionnalites',
        '- Authentification (JWT, 2FA, OAuth)',
        '- Gestion de business (produits, services, commandes)',
        '- Marketplace de modules developpeur',
        '- Publicites (AfriBiz Ads)',
        '- Social Commerce (Stories, Shorts, Lives, Offres Flash)',
        '- Paiements (Mobile Money, Stripe, FedaPay, Escrow, Wallet)',
        '- CRM & Pipeline de ventes',
        '- Messagerie & Notifications (Email, SMS, WhatsApp, Push)',
        '- Formations & E-learning',
        '- Evenements & Reservations',
        '- Livraisons & Logistique',
        '- Comptabilite & Facturation',
        '- Data Hub & Analytics',
        '- Automatisation & Rule Engine',
      ].join('\n'),
      contact: { name: 'Support AfriBiz', email: 'support@afribiz.com' },
    },
    servers: [
      { url: 'http://localhost:3000', description: 'Developpement local' },
      { url: 'https://api.afribiz.com', description: 'Production' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
        csrfToken: { type: 'apiKey', in: 'header', name: 'x-csrf-token' },
      },
      schemas: {
        ApiResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            data: { type: 'object' },
            error: { type: 'string' },
            message: { type: 'string' },
          },
        },
        PaginatedResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            data: { type: 'object' },
            pagination: {
              type: 'object',
              properties: {
                total: { type: 'integer' },
                page: { type: 'integer' },
                limit: { type: 'integer' },
                totalPages: { type: 'integer' },
              },
            },
          },
        },
        ErrorResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            error: { type: 'string', example: "Message d'erreur" },
          },
        },
        LoginRequest: {
          type: 'object',
          required: ['email', 'password'],
          properties: {
            email: { type: 'string', format: 'email', example: 'user@example.com' },
            password: { type: 'string', format: 'password', example: '********' },
          },
        },
        RegisterRequest: {
          type: 'object',
          required: ['email', 'password', 'firstName'],
          properties: {
            email: { type: 'string', format: 'email' },
            password: { type: 'string', format: 'password', minLength: 8 },
            firstName: { type: 'string' },
            lastName: { type: 'string' },
            phone: { type: 'string' },
          },
        },
        PaymentInitRequest: {
          type: 'object',
          required: ['provider', 'amount'],
          properties: {
            provider: {
              type: 'string',
              enum: ['STRIPE', 'FEDAPAY', 'TMONEY', 'FLOOZ', 'WAVE', 'MOOV_MONEY'],
            },
            amount: { type: 'number', example: 5000 },
            phone: { type: 'string' },
            paymentMethodId: { type: 'string' },
            orderId: { type: 'string' },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }, { csrfToken: [] }],
    tags: [
      { name: 'Auth', description: 'Authentification et gestion de compte' },
      { name: 'Utilisateurs', description: 'Gestion des utilisateurs' },
      { name: 'Business', description: 'Profil et parametres business' },
      { name: 'Produits', description: 'Catalogue produits' },
      { name: 'Services', description: 'Catalogue services' },
      { name: 'Commandes', description: 'Commandes clients' },
      { name: 'Paiements', description: 'Paiements et transactions' },
      { name: 'Portefeuille', description: 'Portefeuille et cashback' },
      { name: 'Escrow', description: 'Paiements sequestres' },
      { name: 'Dettes', description: 'Gestion des dettes et reminders' },
      { name: 'Paiements Hybrides', description: 'Paiements multi-methodes' },
      { name: 'Abonnements', description: 'Abonnements business' },
      { name: 'Factures', description: 'Devis et factures' },
      { name: 'Comptabilite', description: 'Comptabilite et rapports financiers' },
      { name: 'Publicites', description: 'AfriBiz Ads' },
      { name: 'Marketplace', description: 'Modules developpeur' },
      { name: 'Stories', description: 'Stories ephemeres' },
      { name: 'Shorts', description: 'Videos courtes' },
      { name: 'Lives', description: 'Livestreaming' },
      { name: 'Offres Flash', description: 'Promotions eclair' },
      { name: 'Favoris', description: 'Favoris utilisateurs' },
      { name: 'Social', description: 'Reseaux sociaux et partage' },
      { name: 'CRM', description: 'CRM et pipeline de ventes' },
      { name: 'Partenaires', description: 'Gestion des partenaires' },
      { name: 'Formations', description: 'E-learning et formations' },
      { name: 'Evenements', description: 'Evenements et reservations' },
      { name: 'Livraisons', description: 'Livraisons et logistique' },
      { name: 'Employes', description: 'Gestion des employes' },
      { name: 'Planning', description: 'Planning et rendez-vous' },
      { name: 'Portfolio', description: 'Portfolio et galerie' },
      { name: 'Litiges', description: 'Gestion des litiges' },
      { name: 'Messagerie', description: 'Messagerie interne' },
      { name: 'Notifications', description: 'Notifications et templates' },
      { name: 'Commentaires', description: 'Commentaires et avis' },
      { name: 'Reactions', description: 'Reactions et likes' },
      { name: 'Signalements', description: 'Signalements de contenu' },
      { name: 'Recherche', description: 'Recherche intelligente' },
      { name: 'Recommandations', description: 'Recommandations personnalisees' },
      { name: 'Croissance', description: 'Growth Engine et coaching' },
      { name: 'Intelligence Client', description: 'Analyse client 360' },
      { name: 'Data Hub', description: 'Analytics et rapports' },
      { name: 'Automatisation', description: 'Rules Engine et automatisation CRM' },
      { name: 'Fidelite', description: 'Programme de fidelite' },
      { name: 'Parrainage', description: 'Programme de parrainage' },
      { name: 'Developpeur', description: 'API developpeur et modules' },
      { name: 'Webhooks', description: 'Webhooks developpeur' },
      { name: 'Signature', description: 'Signature electronique' },
      { name: 'Documents', description: 'Gestion documentaire' },
      { name: 'Upload', description: 'Upload de fichiers' },
      { name: 'Location', description: 'Location de biens' },
      { name: 'Marketing', description: 'Campagnes marketing' },
      { name: 'Admin', description: 'Administration' },
      { name: 'Sante', description: 'Health check et monitoring' },
    ],
  },
  apis: [
    './src/routes/*.ts',
    './src/controllers/*.ts',
    './dist/routes/*.js',
    './dist/controllers/*.js',
  ],
};

export const swaggerSpec = swaggerJsdoc(options);
